language: python
sudo: required
dist: trusty

python:
   - 3.5.2
   - 3.5.3
   - 3.5.4
   - 3.5.5
   - 3.5.6
   - 3.6.0
   - 3.6.1
   - 3.6.2
   - 3.6.3
   - 3.6.4
   - 3.6.5
   - 3.6.6

virtualenv:
    system_site_package: true

script:
 - python -m unittest discover

notifications:
  email:
    - siavashmalektaji@gmail.com