language: python
sudo: required
dist: trusty

python:
  - 3.6
  - 3.5.2
  - 3.5.3
  - 3.5.4

virtualenv:
    system_site_package: true

script:
 - python -m unittest discover

notifications:
  email:
    - siavashmalektaji@gmail.com